from model.dualcoop import DualCoop
from model.FedMPT import FedMPT
from model.custom_coop import CoOpCLIP
from model.custom_vlp import VLPCLIP
from model.positivecoop import PositiveCoop
from model.scpnet import SCPNet
from model.maple import MapleCLIP
from model.tcp import TCPCLIP
from model.fedpgp import FedPGPCLIP
from model.fedawa import FedAWACLIP
from model.fedmvp import FedMVPCLIP
from model.fedmpt import FedMPTCLIP
from model.fedram import FedRAMCLIP