coco_classname = [['person', 'human'],
    ['bicycle', 'bike', 'cycle'],
    ['car', 'taxi', 'auto', 'automobile', 'motor car'], 
    ['motorcycle', 'motor bike', 'motor cycle'], 
    ['airplane', 'aeroplane', "air craft", "jet", "plane", "air plane"], 
    ['bus', 'autobus', 'coach', 'charabanc', 'double decker', 'jitney', 'motor bus', 'motor coach', 'omnibus'],
    ['train', 'rail way', 'railroad'], 
    ['truck'],
    ['boat', 'raft', 'dinghy'],
    ['traffic light'],
    ['fire hydrant', 'fire tap', 'hydrant'],
    ['stop sign', 'halt sign'],
    ['parking meter'],
    ['bench'],
    ['bird'],
    ['cat', 'kitty'],
    ['dog', 'pup', 'puppy', 'doggy'],
    ['horse', 'colt', 'equus'],
    ['sheep'],
    ['cow'],
    ['elephant'],
    ['bear'],
    ['zebra'],
    ['giraffe', 'camelopard'],
    ['backpack', 'back pack', 'knapsack', 'packsack', 'rucksack', 'haversack'],
    ['umbrella'],
    ['handbag', 'hand bag', 'pocketbook', 'purse', 'bag'],
    ['tie', 'necktie'],
    ['suitcase'],
    ['frisbee'],
    ['skis', 'ski'],
    ['snowboard'],
    ['sports ball', 'sport ball', 'ball', 'football', 'soccer', 'tennis', 'basketball', 'baseball'],
    ['kite'],
    ['baseball bat', 'baseball game bat'],
    ['baseball glove', 'baseball mitt', 'baseball game glove'],
    ['skateboard'],
    ['surfboard'],
    ['tennis racket'],
    ['bottle'],
    ['wine glass', 'vino glass'],
    ['cup'],
    ['fork'],
    ['knife'],
    ['spoon'],
    ['bowl'],
    ['banana'],
    ['apple'],
    ['sandwich'],
    ['orange'],
    ['broccoli'],
    ['carrot'],
    ['hot dog'],
    ['pizza'],
    ['donut', 'doughnut'],
    ['cake'],
    ['chair', 'arm chair'],
    ['couch', 'sofa'],
    ['potted plant', 'house plant', 'bonsai', 'pot plant'],
    ['bed'],
    ['dining table', 'dinner table', 'table', 'din table'], 
    ['toilet', 'commode'],
    ['tv', 'tvmonitor', 'monitor', 'television', 'telly'],
    ['laptop'],
    ['mouse'],
    ['remote', 'remote control'],
    ['keyboard', 'typing board'],
    ['cell phone', 'phone', 'mobile phone', 'telephone'],
    ['microwave'],
    ['oven', 'roaster'],
    ['toaster', 'bread-making machine'],
    ['sink', 'basin', 'washbasin'],
    ['refrigerator', 'icebox'],
    ['book','magazine'],
    ['clock','timepiece'],cl
    ['vase', 'flower holder'],
    ['scissors'],
    ['teddy bear', 'teddy', 'teddie bear', 'toy bear'],
    ['hair drier', 'blowing machine', 'hair dryer', 'dryer', 'blow dryer', 'blown dry', 'blow dry', 'hair dry'],
    ['toothbrush'],
]

obj_classname = [
    ['scale'],
    ['tape'],
    ['chicken'],
    ['hurdle'],
    ['game board'],
    ['baozi'],
    ['target'],
    ['plants pot'],
    ['toothbrush'],
    ['projector'],
    ['cheese'],
    ['candy'],
    ['durian'],
    ['dumbbell'],
    ['gas stove'],
    ['lion'],
    ['french fries'],
    ['bench'],
    ['power outlet'],
    ['faucet'],
    ['storage box'],
    ['crab'],
    ['helicopter'],
    ['chainsaw'],
    ['antelope'],
    ['hamimelon'],
    ['jellyfish'],
    ['kettle'],
    ['marker'],
    ['clutch'],
    ['lettuce'],
    ['toilet'],
    ['oven'],
    ['baseball'],
    ['drum'],
    ['hanger'],
    ['toaster'],
    ['bracelet'],
    ['cherry'],
    ['tissue '],
    ['watermelon'],
    ['basketball'],
    ['cleaning products'],
    ['tent'],
    ['fire hydrant'],
    ['truck'],
    ['rice cooker'],
    ['microscope'],
    ['tablet'],
    ['stuffed animal'],
    ['golf ball'],
    ['CD'],
    ['eggplant'],
    ['bowl'],
    ['desk'],
    ['eagle'],
    ['slippers'],
    ['horn'],
    ['carpet'],
    ['notepaper'],
    ['peach'],
    ['saw'],
    ['surfboard'],
    ['facial cleanser'],
    ['corn'],
    ['folder'],
    ['violin'],
    ['watch'],
    ['glasses'],
    ['shampoo'],
    ['pizza'],
    ['asparagus'],
    ['mushroom'],
    ['steak'],
    ['suitcase'],
    ['table tennis  paddle'],
    ['mango'],
    ['boots'],
    ['necklace'],
    ['noodles'],
    ['volleyball'],
    ['baseball bat'],
    ['nuts'],
    ['stroller'],
    ['pumpkin'],
    ['strawberry'],
    ['pear'],
    ['luggage'],
    ['sandals'],
    ['liquid soap'],
    ['handbag'],
    ['flashlight'],
    ['trombone'],
    ['remote'],
    ['shovel'],
    ['ladder'],
    ['cake'],
    ['pomegranate'],
    ['clock'],
    ['vent'],
    ['cymbal'],
    ['iron'],
    ['okra'],
    ['pasta'],
    ['lantern'],
    ['broom'],
    ['fire extinguisher'],
    ['snowboard'],
    ['rice'],
    ['swing'],
    ['cow'],
    ['van'],
    ['tuba'],
    ['book'],
    ['swan'],
    ['lamp'],
    ['race car'],
    ['egg'],
    ['avocado'],
    ['guitar'],
    ['radio'],
    ['sneakers'],
    ['eraser'],
    ['measuring cup'],
    ['sushi'],
    ['deer'],
    ['parrot'],
    ['scissors'],
    ['balloon'],
    ['tortoise'],
    ['meat balls'],
    ['cat'],
    ['electric drill'],
    ['comb'],
    ['sausage'],
    ['bar soap'],
    ['hamburger'],
    ['pepper'],
    ['router'],
    ['spring rolls'],
    ['american football'],
    ['egg tart'],
    ['tape measure'],
    ['banana'],
    ['gun'],
    ['billiards'],
    ['picture'],
    ['paper towel'],
    ['bus'],
    ['goldfish'],
    ['computer box'],
    ['potted plant'],
    ['ship'],
    ['ambulance'],
    ['dog'],
    ['medal'],
    ['butterfly'],
    ['hair dryer'],
    ['globe'],
    ['french horn'],
    ['board eraser'],
    ['tea pot'],
    ['telephone'],
    ['mop'],
    ['broccoli'],
    ['dolphin'],
    ['chair'],
    ['hat'],
    ['tripod'],
    ['traffic light'],
    ['hot dog'],
    ['pot'],
    ['car'],
    ['dining table'],
    ['crosswalk sign'],
    ['tomato'],
    ['barrel'],
    ['washing machine'],
    ['polar bear'],
    ['tie'],
    ['monkey'],
    ['green beans'],
    ['cucumber'],
    ['cookies'],
    ['suv'],
    ['brush'],
    ['carrot'],
    ['tennis racket'],
    ['helmet'],
    ['sink'],
    ['stool'],
    ['flower'],
    ['radiator'],
    ['fishing rod'],
    ['Life saver'],
    ['lighter'],
    ['bread'],
    ['radish'],
    ['human'],
    ['traffic cone'],
    ['knife'],
    ['grapes'],
    ['cellphone'],
    ['trophy'],
    ['urinal'],
    ['cup'],
    ['paint brush'],
    ['mouse'],
    ['soccer'],
    ['cutting'],
    ['wheelchair'],
    ['Accordion'],
    ['goose'],
    ['red cabbage'],
    ['plate'],
    ['saxophone'],
    ['laptop'],
    ['facial mask'],
    ['onion'],
    ['motorbike'],
    ['canned'],
    ['lobster'],
    ['toiletries'],
    ['earphone'],
    ['flag'],
    ['Bread'],
    ['trumpet'],
    ['parking meter'],
    ['garlic'],
    ['skateboard'],
    ['pie'],
    ['barbell'],
    ['yak'],
    ['stapler'],
    ['tangerine'],
    ['zebra'],
    ['traffic sign'],
    ['bottle'],
    ['hotair balloon'],
    ['sailboat'],
    ['llama'],
    ['blackboard'],
    ['coffee machine'],
    ['flute'],
    ['pencil case'],
    ['ice cream'],
    ['combine with bowl'],
    ['kite'],
    ['microphone'],
    ['fork'],
    ['hoverboard'],
    ['blender'],
    ['skating and skiing shoes'],
    ['nightstand'],
    ['toothpaste'],
    ['poker card'],
    ['fan'],
    ['orange'],
    ['chopsticks'],
    ['pig'],
    ['bathtub'],
    ['glove'],
    ['golf club'],
    ['refrigerator'],
    ['rickshaw'],
    ['candle'],
    ['mirror'],
    ['microwave'],
    ['converter'],
    ['airplane'],
    ['lemon'],
    ['head phone'],
    ['tricycle'],
    ['bear'],
    ['backpack'],
    ['apple'],
    ['trolley'],
    ['tong'],
    ['papaya'],
    ['cello'],
    ['camel'],
    ['binoculars'],
    ['cabbage'],
    ['umbrella'],
    ['cigar'],
    ['pomelo'],
    ['cabinet'],
    ['keyboard'],
    ['horse'],
    ['duck'],
    ['combine with glove'],
    ['pine apple'],
    ['potato'],
    ['air conditioner'],
    ['pliers'],
    ['fire truck'],
    ['hockey stick'],
    ['elephant'],
    ['sports car'],
    ['toy'],
    ['mangosteen'],
    ['rabbit'],
    ['bicycle'],
    ['giraffe'],
    ['screwdriver'],
    ['spoon'],
    ['sheep'],
    ['key'],
    ['wine glass'],
    ['treadmill'],
    ['extension cord'],
    ['shrimp'],
    ['ring'],
    ['boat'],
    ['green vegetables'],
    ['coffee table'],
    ['pitaya'],
    ['shark'],
    ['basket'],
    ['wild bird'],
    ['carriage'],
    ['slide'],
    ['fish'],
    ['frisbee'],
    ['hammer'],
    ['printer'],
    ['plum'],
    ['towel'],
    ['camera'],
    ['speaker'],
    ['pickup truck'],
    ['high heels'],
    ['bow tie'],
    ['pigeon'],
    ['coconut'],
    ['machinery vehicle'],
    ['sofa'],
    ['bed'],
    ['tennis ball'],
    ['dates'],
    ['street lights'],
    ['paddle'],
    ['calculator'],
    ['starfish'],
    ['chips'],
    ['train'],
    ['kiwi fruit'],
    ['belt'],
    ['monitor'],
    ['skis'],
    ['leather shoes'],
    ['sandwich'],
    ['Electronic stove and gas stove'],
    ['penguin'],
    ['surveillance camera'],
    ['cue'],
    ['scallop'],
    ['green onion'],
    ['seal'],
    ['crane'],
    ['donkey'],
    ['pen'],
    ['donut'],
    ['pillow'],
    ['trash bin'],
]

voc_classname = [
    ['aeroplane', "air craft", "jet", "plane", "air plane"], 
    ['bicycle', 'bike', 'cycle'], 
    ['bird'], 
    ['boat', 'raft', 'dinghy'],
    ['bottle'], 
    ['bus', 'autobus', 'coach', 'charabanc', 'double decker', 'jitney', 'motor bus', 'motor coach', 'omnibus'], 
    ['car', 'taxi', 'auto', 'automobile', 'motor car'], 
    ['cat', 'kitty'], 
    ['chair', 'arm chair', 'bench'],
    ['cow'], 
    ['diningtable', 'table', 'dining table', 'dinner table', 'din table'],  
    ['dog', 'pup', 'puppy', 'doggy'], 
    ['horse', 'colt', 'equus'],
    ['motorbike', 'motor bike', 'motor cycle'], 
    ['person', 'human', 'people', 'man', 'woman', 'passenger'], 
    ['pottedplant', 'potted plant', 'house plant', 'bonsai', 'pot plant'],
    ['sheep'], 
    ['sofa', 'couch'], 
    ['train', 'rail way', 'railroad'], 
    ['tvmonitor', 'monitor', 'tv', 'television', 'telly']
]

nuswide_classname = [
    ['airport', 'air port', 'air field', 'runway'],
    ['animal'],
    ['beach', 'plage', 'coast', 'seashore'],
    ['bear'],
    ['birds', 'bird'],
    ['boats', 'boat', 'raft', 'dinghy'],
    ['book'],
    ['bridge'],
    ['buildings', 'building'],
    ['cars', 'car'],
    ['castle'],
    ['cat', 'kitty'],
    ['cityscape', 'city', 'skyscraper'],
    ['clouds', 'cloud'],
    ['computer', 'desktop', 'laptop'],
    ['coral'],
    ['cow'],
    ['dancing', 'dance'],
    ['dog', 'pup', 'puppy', 'doggy'],
    ['earthquake', 'collapse building', 'break building', 'broken building'],
    ['elk', 'deer'],
    ['fire'],
    ['fish'],
    ['flags', 'flag'],
    ['flowers','flower'],
    ['food'],
    ['fox'],
    ['frost', 'forsted'],  # 'ice' 'frost'
    ['garden'],
    ['glacier', 'ice'], # 'iceberg'
    ['grass'],
    ['harbor', 'port', 'harbour'],
    ['horses', 'horse'],
    ['house'],
    ['lake'],
    ['leaf'],
    ['map'],
    ['military', 'army' , 'troops', 'troop'],
    ['moon'],
    ['mountain', 'hill'],
    ['nighttime', 'night time', 'night'],
    ['ocean', 'sea'],
    ['person', 'human', 'people', 'man', 'woman', 'passenger'],
    ['plane', 'aeroplane', "air craft", "jet", "air plane"],
    ['plants', 'plant'],
    ['police'],
    ['protest'],
    ['railroad', 'rail road', 'rail way'],
    ['rainbow'],
    ['reflection'],
    ['road', 'path', 'way'],
    ['rocks', 'rock'],
    ['running', 'run'],
    ['sand'],
    ['sign'],
    ['sky'],
    ['snow'],
    ['soccer', 'football'],
    ['sports', 'sport'],
    ['statue'],
    ['street'],
    ['sun'],
    ['sunset'],
    ['surf'],
    ['swimmers', 'swimmer', 'swimming', 'swim'],
    ['tattoo', 'tattooing'],
    ['temple'],
    ['tiger'],
    ['tower'],
    ['town'],
    ['toy'],
    ['train'],
    ['tree'],
    ['valley'],
    ['vehicle'],
    ['water'],
    ['waterfall'],
    ['wedding', 'engagement', 'bride', 'groom'],
    ['whales', 'whale'],
    ['window'],
    ['zebra'],
]